# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9tIzhHDXDgMdM0hvTF22qGqgkwzdmfR
"""

import math

def calc_hexagon_area(side_length):
    return 1.5 * 1.732 * side_length**2

def calc_hexagon_perimeter(side_length):
    return 6 * side_length

def calc_hexagon_angle_sum():
    return 6 * 120

def display_hexagon(side_length):
    print("Hexagon:")
    print("Area:", calc_hexagon_area(side_length))
    print("Perimeter:", calc_hexagon_perimeter(side_length))
    print("Sum of Angles:", calc_hexagon_angle_sum())

def calc_square_area(side_length):
    return side_length**2

def calc_square_perimeter(side_length):
    return 4 * side_length

def display_square(side_length):
    print("Square:")
    print("Area:", calc_square_area(side_length))
    print("Perimeter:", calc_square_perimeter(side_length))

def main():
    cnic_last_digit = int(input("Enter the last digit of your CNIC: "))
    square_side_length = cnic_last_digit + 1
    hexagon_side_length = cnic_last_digit

    while True:
        print("Menu:")
        print("1. Hexagon")
        print("2. Square")
        print("Any other key to exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            display_hexagon(hexagon_side_length)
        elif choice == '2':
            display_square(square_side_length)
        else:
            print("Program terminated.")
            break

if __name__ == "__main__":
    main()