# -*- coding: utf-8 -*-
"""TASK1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SiV_NKEbQG2ljOnjTP8q9QKH-zyc02Hu
"""

# Define arrays to store item information
CATEGORY= ["CASE", "CASE","RAM","RAM","RAM", "Main hard disk drive","Main hard disk drive","Main hard disk drive","Solid State Drive","Solid State Drive","Second Hard Disk Drive","Second Hard Disk Drive","Second Hard Disk Drive","Optical Drive","Optical Drive","Operating System","Operating System"]
item_codes = ["A1", "A2", "B1", "B2", "B3", "C1","C2","C3","D1","D2","E1","E2","E3","F1","F2","G1",'G2']
item_descriptions = ["Compact", "Tower ", "8 GB", "16 GB", "32 GB ", "1 TB HDD","2 TB HDD","4 TB HDD","240 GB SSD","480 GB SSD","1 TB HDD","2 TB HDD","4 TB HDD","DVD/Blu-Ray Playe","DVD/Blu-Ray Re-writer","Standard Version 100.00","Professional Version 175.00"]
item_prices = [75.00, 150.00, 79.99, 149.99, 299.99, 49.99,89.99,129.99,59.99,119.99,49.99,89.99,129.99,50.00,100.00,100.00,175.00]

# Initialize variables to store the customer's choices
chosen_case = None
chosen_ram = None
chosen_hdd = None

# Prompt the customer to choose items
while chosen_case not in item_codes or chosen_ram not in item_codes or chosen_hdd not in item_codes:

    print("Available items:")
    print("CATGORY"+   "  ITEM_CODE"+"  ITEM DESCRIPTION"+"  ITEM PRICE")
    for i in range(0,8):

        print(f"{i + 1}.{CATEGORY[i]}   {item_codes[i]}       {item_descriptions[i]}            ${item_prices[i]}")


    chosen_case = input("Choose a case (Enter item code): ")
    chosen_ram = input("Choose a RAM (Enter item code): ")
    chosen_hdd = input("Choose a Hard Disk Drive (Enter item code): ")

# Calculate the price of the computer
total_price1 = item_prices[item_codes.index(chosen_case)] + item_prices[item_codes.index(chosen_ram)] + item_prices[item_codes.index(chosen_hdd)]

# Output the chosen items and the price of the computer
print("Chosen items:")
print(f"Case: {item_descriptions[item_codes.index(chosen_case)]}")
print(f"RAM: {item_descriptions[item_codes.index(chosen_ram)]}")
print(f"Hard Disk Drive: {item_descriptions[item_codes.index(chosen_hdd)]}")
print(f"Price of the computer: ${total_price}")

print("do you want to purchase from ADDITIONAL ITEMS FROM other categories as well? (Y/N)")
answer=input()
if(answer=="Y"):

  # Initialize variables to store the customer's choices

  chosen_SSD=None
  chosen_SHDD=None
  chosen_OD=None
  chosen_OS=None
  x=0

    # Prompt the customer to choose items
  while x<1 :
      print("Available items:")
      print("CATGORY"+"  ITEM_CODE"+"  ITEM DESCRIPTION"+"  ITEM PRICE")
      for i in range(8,17):


          print(f"{i + 1}.{CATEGORY[i]}   {item_codes[i]}       {item_descriptions[i]}            ${item_prices[i]}")


      chosen_SSD = input("Choose a Solid State Drive(Enter item code): ")
      chosen_SHDD = input("Choose a Second Hard Disk Drive (Enter item code): ")
      chosen_OD = input("Choose a Optical Drive (Enter item code): ")
      chosen_OS = input("Choose a Operating System(Enter item code): ")
      x=x+1
      count=0

      if chosen_SSD is not '':
          count=count+1;
      if chosen_SHDD is not '':
          count=count+1;
      if chosen_OD is not '':
          count=count+1;
      if chosen_OS is not '':
          count=count+1;


  # Calculate the price of the computer
  total_price2 = item_prices[item_codes.index(chosen_case)] + item_prices[item_codes.index(chosen_ram)] + item_prices[item_codes.index(chosen_hdd)]
  total_price3=total_price1+total_price2
  # Output the chosen items and the price of the computer
  print("Chosen items:")
  print(f"SSD: {item_descriptions[item_codes.index(chosen_case)]}")
  print(f"SHDD: {item_descriptions[item_codes.index(chosen_ram)]}")
  print(f"OD: {item_descriptions[item_codes.index(chosen_hdd)]}")
  print(f"OS: {item_descriptions[item_codes.index(chosen_hdd)]}")
  print(f"Price of the computer: ${total_price3}")

  #this code is for discount
  print(f" Cadditional items bought: + {count}")
  if (count==1):
     print(f"Price of the computer(5% discount on): ${total_price3-(total_price3*0.05)}")
  if (count>=2):
     print(f"Price of the computer(10% discount on): ${total_price3-(total_price3*0.1)}")